---
git_protocol: https
editor: nvim
prompt: enabled
pager:
aliases:
    co: pr checkout
    ssh: cs ssh --profile github-codespaces
    log: cs logs --profile github-codespaces
    ssh-gh: cs ssh --profile github-codespaces
    pf: cs ports forward 80:80
http_unix_socket:
browser:
version: "1"
