---
name: Lint Lua files
on: [push, pull_request]  # yamllint disable-line rule:truthy
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1
